name: Slack App Deployment

# Deploy the latest revision of this repo to Slack platform when:
on:
  push:
    branches: [ main ]

jobs:
  build:
    # You can go with any other Linux options if you prefer
    runs-on: ubuntu-latest

    # The deployment process itself usually takes less than 1 minute
    # When your app's code base is larger in the future, you may want to adjust this duration
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

    # Slack CLI requires Deno runtime
    - name: Install Deno runtime
      uses: denoland/setup-deno@11b63cf76cfcafb4e43f97b6cad24d8e8438f62d # v1.5.2
      with:
        # Using the latest stable version along with Slack CLI is recommend
        deno-version: v1.x

    - name: Cache Slack CLI installation
      id: cache-slack
      uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
      with:
        path: |
          /usr/local/bin/slack
          ~/.slack/bin/slack
        key: ${{ runner.os }}-slack
    - name: Install Slack CLI
      if: steps.cache-slack.outputs.cache-hit != 'true'
      run: |
        curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash

    - name: Deploy the app
      env:
        # you can obtain this token string (xoxp-...) by running `slack auth token`
        # Note that this token is connected to a specific Slack workspace/org
        SLACK_SERVICE_TOKEN: ${{ secrets.SLACK_SERVICE_TOKEN }}
      run: |
        slack deploy -s --token $SLACK_SERVICE_TOKEN
        slack trigger update --trigger-id=yyyy
