name: Slack App Deployment

# Deploy the latest revision of this repo to Slack platform when:
on:
  push:
    branches: [ main ]

jobs:
  build:
    # You can go with any other Linux options if you prefer
    runs-on: ubuntu-latest

    # The deployment process itself usually takes less than 1 minute
    # When your app's code base is larger in the future, you may want to adjust this duration
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    # Slack CLI requires Deno runtime
    - name: Install Deno runtime
      uses: denoland/setup-deno@667a34cdef165d8d2b2e98dde39547c9daac7282 # v2.0.4
      with:
        # Using the latest stable version along with Slack CLI is recommend
        deno-version: v1.x

    - name: Cache Slack CLI installation
      id: cache-slack
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: |
          /usr/local/bin/slack
          ~/.slack/bin/slack
        key: ${{ runner.os }}-slack
    - name: Install Slack CLI
      if: steps.cache-slack.outputs.cache-hit != 'true'
      run: |
        curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash

    - name: Deploy the app
      env:
        # you can obtain this token string (xoxp-...) by running `slack auth token`
        # Note that this token is connected to a specific Slack workspace/org
        SLACK_SERVICE_TOKEN: ${{ secrets.SLACK_SERVICE_TOKEN }}
      run: |
        slack deploy -s --token $SLACK_SERVICE_TOKEN
        slack trigger update --trigger-id=yyyy
